version: '3'

services:
  shop_client:
    container_name: shop_client
    hostname: shop_client
    image: shop_client
    build: ./shop_client
    volumes:
      - ./shop_client/app/:/code/shop_client/
      - /code/shop_client/node_modules
    ports: 
      - "3001:3001"

  shop_catalog_service:
    container_name: shop_catalog_service
    hostname: shop_catalog_service
    image: shop_catalog_service
    build: ./shop_catalog_service
    command: >
      sh -c "go install github.com/air-verse/air@v1.52.2 &&
             air"
    env_file:
      - ./shop_catalog_service/.env
    volumes:
      - ./shop_catalog_service/app/:/code/shop_catalog_service/
    ports:
      - "7007:7007"

  shop_catalog_postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shop_catalog_db
    volumes:
      - ./shop_catalog_service/db-data/postgres/:/var/lib/postgresql/data/

  shop_order_service:
    container_name: shop_order_service
    hostname: shop_order_service
    image: shop_order_service
    tty: true
    build: ./shop_order_service
    command: >
      sh -c "npm run dev"
    env_file:
      - ./shop_order_service/.env
    volumes:
      - ./shop_order_service/app/:/code/shop_order_service/
    ports:
      - "7008:7008"

  shop_basket_service:
    container_name: shop_basket_service
    hostname: shop_basket_service
    image: shop_basket_service
    build: ./shop_basket_service
    command: >
      sh -c "go install github.com/air-verse/air@v1.52.2 &&
             air"
    env_file:
      - ./shop_basket_service/.env
    volumes:
      - ./shop_basket_service/app/:/code/shop_basket_service/
    ports:
      - "7009:7009"

  shop_user_service:
    container_name: shop_user_service
    hostname: shop_user_service
    image: shop_user_service
    build: ./shop_user_service
    command: >
      sh -c "go install github.com/air-verse/air@v1.52.2 &&
             air"
    env_file:
      - ./shop_user_service/.env
    volumes:
      - ./shop_user_service/app/:/code/shop_user_service/
    ports:
      - "7010:7010"

  shop_db_mongo:
    container_name: shop_db_mongo
    hostname: shop_db_mongo
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      DB_NAME: som_db
      DB_USERNAME: admin
      DB_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
