version: "3"

services:
  shop_client:
    container_name: shop_client
    hostname: shop_client
    image: shop_client
    build: ./shop_client
    volumes:
      - ./shop_client/app/:/code/shop_client/
      - /code/shop_client/node_modules
    ports:
      - 3001:3001

  shop_catalog_service:
    container_name: shop_catalog_service
    hostname: shop_catalog_service
    image: shop_catalog_service
    build: ./shop_catalog_service
    command: >
      sh -c "go install github.com/air-verse/air@v1.52.2 &&
            ./scripts migrate-up &&
            ./scripts migrate-dev-data &&
             air"
    env_file:
      - ./shop_catalog_service/.env
    volumes:
      - ./shop_catalog_service/app/:/code/shop_catalog_service/
    ports:
      - 7007:7007

  shop_catalog_postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shop_catalog_db
    volumes:
      - ./shop_catalog_service/db-data/postgres/:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  shop_order_service:
    container_name: shop_order_service
    hostname: shop_order_service
    image: shop_order_service
    build: ./shop_order_service
    command: >
      sh -c "go install github.com/air-verse/air@v1.52.2 &&
             air"
    env_file:
      - ./shop_order_service/.env
    volumes:
      - ./shop_order_service/app/:/code/shop_order_service/
    ports:
      - 7009:7009

  shop_user_service:
    container_name: shop_user_service
    hostname: shop_user_service
    image: shop_user_service
    build: ./shop_user_service
    command: >
      sh -c "go install github.com/air-verse/air@v1.52.2 &&
             air"
    env_file:
      - ./shop_user_service/.env
    volumes:
      - ./shop_user_service/app/:/code/shop_user_service/
    ports:
      - 7010:7010

  shop_db_mongo:
    container_name: shop_db_mongo
    hostname: shop_db_mongo
    image: mongo:7.0
    environment:
      DB_NAME: som_db
      DB_USERNAME: admin
      DB_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
    ports:
      - 27017:27017

  shop_redis:
    container_name: shop_redis
    hostname: shop_redis
    image: redis:7.4
    command: redis-server --save 20 1 --loglevel warning --requirepass q2sGPHduXqKHSsYlz59FF9i7hc8VUraQ
    volumes:
      - ./cache:/data
    ports:
      - 6379:6379

  nats:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    ports:
      - 8222:8222
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: root
      GF_SECURITY_ADMIN_PASSWORD: password
    ports:
      - 3000:3000
